//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace org::alljoyn::example::Rover;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<RoverLeftResult^>^ RoverServiceEventAdapter::LeftAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverLeftCalledEventArgs(info);
    LeftCalled(this, args);
    return RoverLeftCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverRightResult^>^ RoverServiceEventAdapter::RightAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverRightCalledEventArgs(info);
    RightCalled(this, args);
    return RoverRightCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverForwardResult^>^ RoverServiceEventAdapter::ForwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverForwardCalledEventArgs(info);
    ForwardCalled(this, args);
    return RoverForwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverBackwardResult^>^ RoverServiceEventAdapter::BackwardAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverBackwardCalledEventArgs(info);
    BackwardCalled(this, args);
    return RoverBackwardCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverStopResult^>^ RoverServiceEventAdapter::StopAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverStopCalledEventArgs(info);
    StopCalled(this, args);
    return RoverStopCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverAutonomousResult^>^ RoverServiceEventAdapter::AutonomousAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverAutonomousCalledEventArgs(info);
    AutonomousCalled(this, args);
    return RoverAutonomousCalledEventArgs::GetResultAsync(args);
}

IAsyncOperation<RoverManualResult^>^ RoverServiceEventAdapter::ManualAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new RoverManualCalledEventArgs(info);
    ManualCalled(this, args);
    return RoverManualCalledEventArgs::GetResultAsync(args);
}

// Property Reads
// Property Writes
